### ISSUE TITLE
Invalid selector

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/gpi_core-feedstock#3]
The [selector used with `skip`]( https://github.com/conda-forge/gpi_core-feedstock/blob/b91acc6469fe685a8cd0ef6c5f8f27bd416b8c02/recipe/meta.yaml#L17 ) is invalid. This should use `and`/`or` instead of `,`. As a result, it appears all builds have been skipped and packages don't appear to be uploaded.

**Comment by borupdaniel** [comment]
Thanks for catching this, @jakirkham!
